# SPDX-FileCopyrightText: 2015-2019 Tailordev
# SPDX-FileCopyrightText: 2020 The tt Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: MIT

language: python

matrix:
    include:
        - python: 3.7
          os: linux
          dist: xenial
          env: TOXENV=flake8
        - python: 3.5
          os: linux
          dist: trusty
          env: TOXENV=py35
        - python: 3.6
          os: linux
          dist: trusty
          env: TOXENV=py36
        - python: 3.7
          os: linux
          dist: xenial
          env: TOXENV=py37

install:
  - pip install tox

script:
  - tox -e "${TOXENV}"
