# SPDX-FileCopyrightText: 2015-2019 Tailordev
# SPDX-FileCopyrightText: 2020 The tt Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: MIT

site_name: tt
theme: flatly
repo_url: https://gitlab.com/davidalfonso/tt
repo_name: GitLab
site_description: A wonderful CLI to track your time!
site_author: David Alfonso
copyright: >
  tt, by David Alfonso, is released under the MIT License.
nav:
- Home: 'index.md'
- User Guide:
    - Commands: 'user-guide/commands.md'
    - Configuration: 'user-guide/configuration.md'
- Contributing:
    - Howto: 'contributing/how-to.md'
    - Hack: 'contributing/hack.md'
    - Pull Request guidelines: 'contributing/pr-guidelines.md'
    - Code of Conduct: 'contributing/coc.md'
    - Release a new version: 'contributing/release-new-version.md'
- FAQ: 'faq.md'
- About:
    - License: 'about/license.md'
    - Release notes: 'about/release-notes.md'
extra_css:
    - css/tt.css
markdown_extensions:
    - attr_list
    - smarty
